version: "3"

services:
   postgres:
      image: postgres:latest
      volumes:
       - db-data:/data/postgress
       - db-dump:/data/dump
      ports:
       - 5432:5432
      environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: school
       POSTGRES_DB: school
       POSTGRES_HOST: db
      networks:
       - docker-practice-net

   redis:
     image: redis:latest
     ports:
      - 6379:6379
     environment:
      - REDIS_REPLICATION_MODE=master
     networks:
      - docker-practice-net

   app:
    image: docker-lesson
    ports:
      - 8888:8080
      - 5005:5005
    volumes:
     - ./app:/app
    working_dir: /app
    networks:
      - docker-practice-net
    depends_on:
      - postgres
      - redis

networks:
   docker-practice-net:
volumes:
   db-data:
   db-dump:
