version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=school

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    image: app
    depends_on:
      - db
      - redis
    ports:
      - "8888:8888"